### PR TITLE
Path to private_user.h updated

### PR DESCRIPTION
**Pull request by pierreboissinot**

### CODE REVIEW

**Comment by blackccpie** [comment]
Pierre, the path was wrong indeed. But I think the correct path should be `src/deezer_wrapper/private/private_user.h`, isn’t it?

**Comment by pierreboissinot** [comment]
Oh yeah you're right, it's: ```deezzy/src/deezer_wrapper/private/private_user.h```

**Comment by blackccpie** [comment]
@pierreboissinot, could you please commit this update to your branch so that I can accept your pull request? thx

**Comment by pierreboissinot** [comment]
Hi @blackccpie , it's done

**Comment by blackccpie** [comment]
Hi @pierreboissinot, I think your commit is in your master branch, as I don't see it in this pull request. Maybe you should merge it to your *patch-1* branch?

**Comment by pierreboissinot** [comment]
Ok @blackccpie , it should be fine now ^^.

**Pull request merged**
